// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

#pragma once

#ifndef GQLOBJECTS_H
#define GQLOBJECTS_H

#include "GQLSchema.h"

#include "QueryObject.h"
#include "AuthorObject.h"

#endif // GQLOBJECTS_H
